
manual_control_node:

  ros__parameters:

    # Kecepatan linear saat tekan W/S (m/s)

    # Akan dikonversi ke unit PLC oleh kinematics_node

    linear_speed: 1.0



    # Kecepatan angular saat tekan A/D (rad/s)

    angular_speed: 1.66



    # Rate publikasi /cmd_vel (Hz)

    publish_hz: 10.0

